version: "3.7"

services:
  app_proxy:
    environment:
      # The format here is: <app-id>_<service-name>_1
      APP_HOST: upsnap_server_1
      APP_PORT: 5000

  upsnap:
    image: ghcr.io/seriousm4x/upsnap:4
    restart: unless-stopped
    volumes:
      - ${APP_DATA_DIR}/data:/app/pb_data
    environment:
      TZ: Europe/Copenhagen # Adjust to your timezone
      UPSNAP_INTERVAL: "@every 10s" # Interval for device pings
      UPSNAP_SCAN_RANGE: 192.168.1.0/24 # Adjust to your network range
    user: "1000:1000"
    init: true
    ports:
      - "5000:5000" # Expose port 5000
