version: '3.7'

services:
  server:
    image: ghcr.io/seriousm4x/upsnap:4
    command:
      - './upsnap serve --http 0.0.0.0:5000'
    restart: on-failure
    network_mode: host
    volumes:
      - ${APP_DATA_DIR}/data:/app/pb_data
    environment:
      - TZ=Europe/Berlin
      - UPSNAP_INTERVAL=@every 10s
      - UPSNAP_SCAN_RANGE=192.168.1.0/24
      - UPSNAP_SCAN_TIMEOUT=500ms
      - UPSNAP_PING_PRIVILEGED=true
      - UPSNAP_WEBSITE_TITLE=UpSnap
    cap_add:
      - NET_ADMIN
    container_name: epic-umbrel-app-store-upsnap_server_1
