version: "3.7"

services:
  app_proxy:
    environment:
      # Reference by service name instead of container name
      APP_HOST: server
      APP_PORT: 3000

  server:
    image: ghcr.io/seriousm4x/upsnap:3.7  # Changed to match version 3.7
    network_mode: host
    restart: unless-stopped
    volumes:
      - ${APP_DATA_DIR}/data:/app/pb_data
    environment:
      - TZ=Europe/Berlin
      - UPSNAP_INTERVAL=@every 10s
      - UPSNAP_SCAN_RANGE=192.168.1.0/24
      - UPSNAP_SCAN_TIMEOUT=500ms
      - UPSNAP_PING_PRIVILEGED=true
      - UPSNAP_WEBSITE_TITLE=UpSnap
    cap_add:
      - NET_ADMIN
      - NET_RAW  # Added for better network capabilities
