version: "3.7"

services:

  app_proxy:
    environment:
      # The format here is: <app-id>_<docker-service-name>_1
      APP_HOST: epic-umbrel-app-store_upsnap-server_1
      APP_PORT: 3000
    
  server:
  image: ghcr.io/seriousm4x/upsnap:4
     network_mode: host
     restart: unless-stopped
     volumes:
       - ${APP_DATA_DIR}/data:/app/pb_data
     environment:
       - TZ=Europe/Berlin
       - UPSNAP_INTERVAL=@every 10s
       - UPSNAP_SCAN_RANGE=192.168.1.0/24
       - UPSNAP_SCAN_TIMEOUT=500ms
       - UPSNAP_PING_PRIVILEGED=true
       - UPSNAP_WEBSITE_TITLE=UpSnap
     cap_add:
       - NET_ADMIN
